CREATE OR ALTER FUNCTION [___SCHEMA_NAME___].[decode] (@binary varbinary(max))
RETURNS VARCHAR(MAX)
AS
BEGIN
    RETURN CAST(DECOMPRESS(@binary) AS VARCHAR(MAX)) COLLATE Latin1_General_100_CS_AS_KS_WS_SC_UTF8
END