import { map as map_1, defaultArg } from "../../../../../AppSample2/src/fable_modules/fable-library.3.7.6/Option.js";
import { Helpers_extractProp } from "../../../../../LibClient/src/ReactXP/ReactXPBindings.fs.js";
import { injectImplicitProps, prepareStylesForPassingToReactXpComponent, findApplicableStyles, mergeComponentAndPropsStyles } from "../../../../../LibClient/src/ReactXP/Styles/Runtime.fs.js";
import { RenderResult_ToRawElements, RenderResult_ToLeaves_410EF94B, RenderResult_Make_2B31D457, RenderResult_Make_Z1C694E5A, RenderResult, RenderResult_Make_6E3A73D, RenderResult_Make_410EF94B, nthChildClasses, RenderResult_Make_E25108F, RenderResult_ToRawElementsSingle, RenderResult_ToSingleElement_6E3A73D } from "../../../../../LibClient/src/RenderResult.fs.js";
import { Microsoft_FSharp_Collections_FSharpList$1__List$1_get_IsNonempty } from "../../../../../LibLangFsharp/src/ListExtensions.fs.js";
import { Make } from "../../../../../LibClient/src/ReactXP/Components/View/View.typext.fs.js";
import { ReactXP_Components_TypeExtensions_TEs__TEs_MakeViewProps_Static_1BFB6755 } from "../../../../../LibClient/src/_autogenerated_/ReactXP/Components/View/View.TypeExtensions.fs.js";
import { map, empty, singleton, append, delay, toList } from "../../../../../AppSample2/src/fable_modules/fable-library.3.7.6/Seq.js";
import { ofArray, reverse, singleton as singleton_1, ofSeq, empty as empty_1, isEmpty } from "../../../../../AppSample2/src/fable_modules/fable-library.3.7.6/List.js";
import { Option_getOrElse } from "../../../../../LibLangFsharp/src/OptionExtensions.fs.js";
import { Navigation$3__Close } from "../../../Components/With/Navigation/Navigation.typext.fs.js";
import { DialogsState$1__TryGetAdHoc_5227FA81, DialogsState$1__TryGetResultful_5227FA81 } from "../../../RoutesSpec.fs.js";

export function render(props, estate, pstate, actions, __componentStyles) {
    [props, estate, void 0, actions];
    const __class = defaultArg(Helpers_extractProp("ClassName", props), "");
    const __mergedStyles = mergeComponentAndPropsStyles(__componentStyles, props);
    const __parentFQN = void 0;
    return RenderResult_ToSingleElement_6E3A73D(RenderResult_ToRawElementsSingle(__parentFQN, Microsoft_FSharp_Collections_FSharpList$1__List$1_get_IsNonempty(props.Dialogs) ? RenderResult_Make_E25108F((tupledArg) => {
        let __currExplicitProps, __currClass, __currStyles, __implicitProps, __list_6;
        const __sibI = tupledArg[0] | 0;
        const __sibC = tupledArg[1] | 0;
        const __pFQN = tupledArg[2];
        const __parentFQN_1 = "ReactXP.Components.View";
        return Make((__currExplicitProps = ReactXP_Components_TypeExtensions_TEs__TEs_MakeViewProps_Static_1BFB6755(), (__currClass = ("view" + nthChildClasses(__sibI, __sibC)), (__currStyles = findApplicableStyles(__mergedStyles, __currClass), (__implicitProps = toList(delay(() => append((__currClass !== "") ? singleton(["ClassName", __currClass]) : empty(), delay(() => ((!isEmpty(__currStyles)) ? singleton(["style", prepareStylesForPassingToReactXpComponent("ReactXP.Components.View", __currStyles)]) : empty()))))), injectImplicitProps(__implicitProps, __currExplicitProps))))))((__list_6 = ofArray([RenderResult_Make_E25108F((tupledArg_1) => {
            let __currExplicitProps_1, __currClass_1, __currStyles_1, __implicitProps_1;
            const __sibI_1 = tupledArg_1[0] | 0;
            const __sibC_1 = tupledArg_1[1] | 0;
            const __pFQN_1 = tupledArg_1[2];
            const __parentFQN_2 = "ReactXP.Components.View";
            return Make((__currExplicitProps_1 = ReactXP_Components_TypeExtensions_TEs__TEs_MakeViewProps_Static_1BFB6755(), (__currClass_1 = ("sentinel" + nthChildClasses(__sibI_1, __sibC_1)), (__currStyles_1 = findApplicableStyles(__mergedStyles, __currClass_1), (__implicitProps_1 = toList(delay(() => append((__currClass_1 !== "") ? singleton(["ClassName", __currClass_1]) : empty(), delay(() => ((!isEmpty(__currStyles_1)) ? singleton(["style", prepareStylesForPassingToReactXpComponent("ReactXP.Components.View", __currStyles_1)]) : empty()))))), injectImplicitProps(__implicitProps_1, __currExplicitProps_1))))))(empty_1());
        }), RenderResult_Make_410EF94B(ofSeq(map((dialog) => RenderResult_Make_E25108F((tupledArg_2) => {
            let __currExplicitProps_2, __currClass_2, __currStyles_2, __implicitProps_2, __list_5, token_1, __list_2, token_2, __list_4, token, resultlessDialog, __list;
            const __sibI_2 = tupledArg_2[0] | 0;
            const __sibC_2 = tupledArg_2[1] | 0;
            const __pFQN_2 = tupledArg_2[2];
            const __parentFQN_3 = "ReactXP.Components.View";
            return Make((__currExplicitProps_2 = ReactXP_Components_TypeExtensions_TEs__TEs_MakeViewProps_Static_1BFB6755(), (__currClass_2 = ("frame" + nthChildClasses(__sibI_2, __sibC_2)), (__currStyles_2 = findApplicableStyles(__mergedStyles, __currClass_2), (__implicitProps_2 = toList(delay(() => append((__currClass_2 !== "") ? singleton(["ClassName", __currClass_2]) : empty(), delay(() => ((!isEmpty(__currStyles_2)) ? singleton(["style", prepareStylesForPassingToReactXpComponent("ReactXP.Components.View", __currStyles_2)]) : empty()))))), injectImplicitProps(__implicitProps_2, __currExplicitProps_2))))))((__list_5 = singleton_1((dialog.tag === 0) ? ((token_1 = dialog.fields[0], RenderResult_Make_6E3A73D((__list_2 = singleton_1(Option_getOrElse(new RenderResult(0), map_1((resultfulDialog) => {
                let __list_1;
                return RenderResult_Make_410EF94B(singleton_1(RenderResult_Make_Z1C694E5A((__list_1 = singleton_1(RenderResult_Make_2B31D457(props.MakeResultful([resultfulDialog, (arg10_2) => ((arg20_1) => {
                    Navigation$3__Close(props.Nav, token_1, arg10_2, arg20_1);
                })]))), RenderResult_ToLeaves_410EF94B(__list_1)))));
            }, DialogsState$1__TryGetResultful_5227FA81(props.DialogsState, token_1)))), RenderResult_ToRawElements(__parentFQN_3, __list_2))))) : ((dialog.tag === 2) ? ((token_2 = dialog.fields[0], RenderResult_Make_6E3A73D((__list_4 = singleton_1(Option_getOrElse(new RenderResult(0), map_1((adHocCloseToDialog) => {
                let __list_3;
                return RenderResult_Make_410EF94B(singleton_1(RenderResult_Make_Z1C694E5A((__list_3 = singleton_1(RenderResult_Make_2B31D457(adHocCloseToDialog((arg10_4) => ((arg20_2) => {
                    Navigation$3__Close(props.Nav, token_2, arg10_4, arg20_2);
                })))), RenderResult_ToLeaves_410EF94B(__list_3)))));
            }, DialogsState$1__TryGetAdHoc_5227FA81(props.DialogsState, token_2)))), RenderResult_ToRawElements(__parentFQN_3, __list_4))))) : ((token = dialog.fields[0], (resultlessDialog = dialog.fields[1], RenderResult_Make_6E3A73D((__list = singleton_1(RenderResult_Make_2B31D457(props.MakeResultless([resultlessDialog, (arg10) => ((arg20) => {
                Navigation$3__Close(props.Nav, token, arg10, arg20);
            })]))), RenderResult_ToRawElements(__parentFQN_3, __list)))))))), RenderResult_ToRawElements(__parentFQN_3, __list_5)));
        }), reverse(props.Dialogs))))]), RenderResult_ToRawElements(__parentFQN_1, __list_6)));
    }) : (new RenderResult(0))));
}

