IF NOT EXISTS
    (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
     WHERE COLUMN_NAME = 'LifeCycleName'
     AND TABLE_NAME = '___LIFECYCLE_NAME____Subscription'
     AND TABLE_SCHEMA = '___SCHEMA_NAME___'
     AND CHARACTER_MAXIMUM_LENGTH >= 80)
BEGIN
ALTER TABLE [___SCHEMA_NAME___].[___LIFECYCLE_NAME____Subscription]
ALTER COLUMN [LifeCycleName] NVARCHAR(80) COLLATE Latin1_General_CS_AS_KS_WS NOT NULL;
END

IF NOT EXISTS
    (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
     WHERE COLUMN_NAME = 'CallerLifeCycleName'
     AND TABLE_NAME = '___LIFECYCLE_NAME____CallDedup'
     AND TABLE_SCHEMA = '___SCHEMA_NAME___'
     AND CHARACTER_MAXIMUM_LENGTH >= 80)
BEGIN
ALTER TABLE [___SCHEMA_NAME___].[___LIFECYCLE_NAME____CallDedup]
ALTER COLUMN [CallerLifeCycleName] NVARCHAR(80) COLLATE Latin1_General_CS_AS_KS_WS NOT NULL;
END
