IF NOT EXISTS
   (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
   WHERE COLUMN_NAME = 'SideEffectTarget'
    AND TABLE_NAME = '___LIFECYCLE_NAME____SideEffect'
    AND TABLE_SCHEMA = '___SCHEMA_NAME___')
BEGIN
    ALTER TABLE [___SCHEMA_NAME___].[___LIFECYCLE_NAME____SideEffect]
    ADD [SideEffectTarget] NVARCHAR(MAX) COLLATE Latin1_General_CS_AS_KS_WS NULL;
END
